{
  "openapi" : "3.0.0",
  "servers" : [ {
    "url" : "https://api.gab.ai/v1.0/"
  } ],
  "info" : {
    "version" : "1.0.0-oas3",
    "title" : "Gab.ai API",
    "contact" : {
      "email" : "developers@gab.ai"
    }
  },
  "paths" : {
    "/feed" : {
      "get" : {
        "security" : [ {
          "oauth2" : [ "read" ]
        } ],
        "tags" : [ "Home Feed" ],
        "description" : "For attaching GIFs and media attachments, you need to check out related endpoints."
      }
    },
    "/popular/feed" : {
      "get" : {
        "tags" : [ "Popular" ],
        "description" : "Popular posts."
      }
    },
    "/popular/users" : {
      "get" : {
        "security" : [ {
          "oauth2" : [ "read" ]
        } ],
        "tags" : [ "Popular" ],
        "description" : "Popular users."
      }
    },
    "/users/{username}" : {
      "get" : {
        "security" : [ {
          "oauth2" : [ "read" ]
        } ],
        "tags" : [ "Details of a user" ]
      }
    },
    "/users/{username}/followers" : {
      "get" : {
        "security" : [ {
          "oauth2" : [ "read" ]
        } ],
        "tags" : [ "Details of a user" ]
      }
    },
    "/users/{username}/following" : {
      "get" : {
        "security" : [ {
          "oauth2" : [ "read" ]
        } ],
        "tags" : [ "Details of a user" ]
      }
    },
    "/users/{username}/feed" : {
      "get" : {
        "security" : [ {
          "oauth2" : [ "read" ]
        } ],
        "tags" : [ "Details of a user" ],
        "description" : "Returns posts of a user"
      }
    },
    "/users/{username}/follow" : {
      "post" : {
        "security" : [ {
          "oauth2" : [ "engage-user" ]
        } ],
        "tags" : [ "Actions for a user" ]
      },
      "delete" : {
        "security" : [ {
          "oauth2" : [ "engage-user" ]
        } ],
        "tags" : [ "Actions for a user" ]
      }
    },
    "/users/{username}/mute" : {
      "post" : {
        "security" : [ {
          "oauth2" : [ "engage-user" ]
        } ],
        "tags" : [ "Actions for a user" ]
      },
      "delete" : {
        "security" : [ {
          "oauth2" : [ "engage-user" ]
        } ],
        "tags" : [ "Actions for a user" ]
      }
    },
    "/posts/{post-id}/like" : {
      "post" : {
        "security" : [ {
          "oauth2" : [ "engage-post" ]
        } ],
        "tags" : [ "Actions for a post" ]
      },
      "delete" : {
        "security" : [ {
          "oauth2" : [ "engage-post" ]
        } ],
        "tags" : [ "Actions for a post" ]
      }
    },
    "/posts/{post-id}/dislike" : {
      "post" : {
        "security" : [ {
          "oauth2" : [ "engage-post" ]
        } ],
        "tags" : [ "Actions for a post" ]
      },
      "delete" : {
        "security" : [ {
          "oauth2" : [ "engage-post" ]
        } ],
        "tags" : [ "Actions for a post" ]
      }
    },
    "/posts/{post-id}/repost" : {
      "post" : {
        "security" : [ {
          "oauth2" : [ "engage-post" ]
        } ],
        "tags" : [ "Actions for a post" ]
      },
      "delete" : {
        "security" : [ {
          "oauth2" : [ "engage-post" ]
        } ],
        "tags" : [ "Actions for a post" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "description" : "This API uses OAuth 2 with the authorization code grant flow.",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://api.gab.ai/oauth/authorize",
            "tokenUrl" : "https://api.gab.ai/oauth/token",
            "scopes" : {
              "read" : "Read access to your profile and feeds",
              "engage-user" : "Follow or mute users",
              "engage-post" : "Vote, repost or report posts",
              "notifications" : "Access notifications"
            }
          }
        }
      }
    }
  }
}